--- 
text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml', 'coffee', 'cr' ]
output_dir: output
data_sources: 
- type: filesystem_unified
  items_root: /
  layouts_root: /

# Custom settings

# site info
base_url: http://nanoc-blog-kit.mgutz.com
site_name: Your Site
site_description: Your site starter kit

# number of posts to display on index page (front)
index_count: 5

# length of content for excerption
excerpt_len: 200

# DISQUS Site Shortname. Comment out to disable.
disqus_shortname: 

# Use rsync + ssh for live site. To deploy:
#
#   % rake deploy:rsync
deploy:
  default:
    dst: "mgutz_com:www/nanoc3_blog"
    options: ['-ave ssh', '--exclude=.DS_Store', '--exclude=*~']
